{
 "title": "KubeVirt Top Consumers",
 "tags": [ "kubevirt-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Top Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Top Consumers of Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum (avg_over_time(kubevirt_vmi_memory_available_bytes[$__range]) - avg_over_time(kubevirt_vmi_memory_usable_bytes[$__range]))by(name, namespace)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of CPU by virt-launcher Pods",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[$__range])) by (namespace,pod)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of Storage Traffic",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_read_traffic_bytes_total[$__range]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total[$__range])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of Storage IOPS",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_storage_iops_read_total[$__range]) + rate(kubevirt_vmi_storage_iops_write_total[$__range])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of Network Traffic",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_network_receive_bytes_total[$__range]) + rate(kubevirt_vmi_network_transmit_bytes_total[$__range])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of vCPU Wait",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(rate(kubevirt_vmi_vcpu_wait_seconds_total[$__range])) by (namespace, name)))>0"
    }
   ]
  },
  {
   "title": "Top Consumers of Memory Swap Traffic",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum(avg_over_time(kubevirt_vmi_memory_swap_in_traffic_bytes[$__range]) + avg_over_time(kubevirt_vmi_memory_swap_out_traffic_bytes[$__range])) by (namespace, name)))>0"
    }
   ]
  },
  { "title": "Top Consumers Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Usage by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(topk(5, sum (avg_over_time(kubevirt_vmi_memory_available_bytes[$__rate_interval]) - avg_over_time(kubevirt_vmi_memory_usable_bytes[$__rate_interval]))by(name, namespace)))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Usage by virt-launcher Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(container_cpu_usage_seconds_total{container=\"compute\",pod=~\"virt-launcher-.*\"}[$__rate_interval])) by (pod, namespace))>0",
     "legendFormat": "{{pod}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Storage Traffic by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_storage_read_traffic_bytes_total[$__rate_interval]) + irate(kubevirt_vmi_storage_write_traffic_bytes_total[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Storage IOPS Usage by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_storage_iops_read_total[$__rate_interval]) + irate(kubevirt_vmi_storage_iops_write_total[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Network Traffic by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_network_receive_bytes_total[$__rate_interval]) + irate(kubevirt_vmi_network_transmit_bytes_total[$__rate_interval])) by (namespace, name))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "vCPU Wait by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort_desc(sum(irate(kubevirt_vmi_vcpu_wait_seconds_total{}[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Swap Traffic by Virtual Machines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum(avg_over_time(kubevirt_vmi_memory_swap_in_traffic_bytes{}[$__rate_interval]) + avg_over_time(kubevirt_vmi_memory_swap_out_traffic_bytes{}[$__rate_interval])) by (name, namespace))>0",
     "legendFormat": "{{name}} / {{namespace}}"
    }
   ]
  }
 ]
}